// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

class Routes {
  const Routes._();

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>>(required) keyValue]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
