// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://Excel',
  'fluttercandies://FrozenedRowColumn',
  'fluttercandies://HugeDataDemo',
  'fluttercandies://StockList',
  'fluttercandies://TabView',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

class Routes {
  const Routes._();

  /// 'Excel'
  ///
  /// [name] : 'fluttercandies://Excel'
  ///
  /// [routeName] : 'Excel'
  ///
  /// [description] : 'Excel'
  ///
  /// [constructors] :
  ///
  /// ExcelDemo : [Key key]
  ///
  /// [exts] : {group: Complex, order: 0}
  static const String fluttercandiesExcel = 'fluttercandies://Excel';

  /// 'FrozenedRowColumn'
  ///
  /// [name] : 'fluttercandies://FrozenedRowColumn'
  ///
  /// [routeName] : 'FrozenedRowColumn'
  ///
  /// [description] : 'FrozenedRowColumn'
  ///
  /// [constructors] :
  ///
  /// FrozenedRowColumn : [Key key, SyncPageController syncPageController]
  ///
  /// [exts] : {group: Simple, order: 0}
  static const String fluttercandiesFrozenedRowColumn =
      'fluttercandies://FrozenedRowColumn';

  /// 'HugeDataDemo'
  ///
  /// [name] : 'fluttercandies://HugeDataDemo'
  ///
  /// [routeName] : 'HugeDataDemo'
  ///
  /// [description] : 'HugeDataDemo'
  ///
  /// [constructors] :
  ///
  /// HugeDataDemo : [Key key]
  ///
  /// [exts] : {group: Simple, order: 2}
  static const String fluttercandiesHugeDataDemo =
      'fluttercandies://HugeDataDemo';

  /// 'StockList'
  ///
  /// [name] : 'fluttercandies://StockList'
  ///
  /// [routeName] : 'StockList'
  ///
  /// [description] : 'StockList'
  ///
  /// [constructors] :
  ///
  /// StockList : [Key key]
  ///
  /// [exts] : {group: Complex, order: 1}
  static const String fluttercandiesStockList = 'fluttercandies://StockList';

  /// 'TabView'
  ///
  /// [name] : 'fluttercandies://TabView'
  ///
  /// [routeName] : 'TabView'
  ///
  /// [description] : 'TabView'
  ///
  /// [constructors] :
  ///
  /// TabView : [Key key]
  ///
  /// [exts] : {group: Simple, order: 1}
  static const String fluttercandiesTabView = 'fluttercandies://TabView';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>>(required) keyValue]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
